const bancoDeProdutos = [
    { id: 1, titulo: "The Dark Side of the Moon", artista: "Pink Floyd", ano: "1973", preco: "R$ 189,00", categoria: "disco", peso: 450, estado: "EE", capa: "fotos/prod-1-frente.jpg", verso: "fotos/prod-1-verso.jpg" },
    { id: 2, titulo: "Racional - Vol. 1", artista: "Tim Maia", ano: "1975", preco: "R$ 220,00", categoria: "disco", peso: 450, estado: "LAC", capa: "fotos/prod-2-frente.jpg", verso: "fotos/prod-2-verso.jpg" },
    { id: 3, titulo: "Abbey Road", artista: "The Beatles", ano: "1969", preco: "R$ 199,00", categoria: "disco", peso: 450, estado: "EE", capa: "fotos/prod-3-frente.jpg", verso: "fotos/prod-3-verso.jpg" },
    { id: 4, titulo: "Led Zeppelin IV", artista: "Led Zeppelin", ano: "1971", preco: "R$ 180,00", categoria: "disco", peso: 450, estado: "EE", capa: "fotos/prod-4-frente.jpg", verso: "fotos/prod-4-verso.jpg" },
    { id: 5, titulo: "A Tábua de Esmeralda", artista: "Jorge Ben", ano: "1974", preco: "R$ 210,00", categoria: "disco", peso: 450, estado: "LAC", capa: "fotos/prod-5-frente.jpg", verso: "fotos/prod-5-verso.jpg" },
    { id: 6, titulo: "Secos & Molhados", artista: "Secos & Molhados", ano: "1973", preco: "R$ 175,00", categoria: "disco", peso: 450, estado: "EE", capa: "fotos/prod-6-frente.jpg", verso: "fotos/prod-6-verso.jpg" },
    { id: 7, titulo: "Master of Puppets", artista: "Metallica", ano: "1986", preco: "R$ 230,00", categoria: "disco", peso: 450, estado: "EE", capa: "fotos/prod-7-frente.jpg", verso: "fotos/prod-7-verso.jpg" },
    { id: 8, titulo: "Back in Black", artista: "AC/DC", ano: "1980", preco: "R$ 190,00", categoria: "disco", peso: 450, estado: "LAC", capa: "fotos/prod-8-frente.jpg", verso: "fotos/prod-8-verso.jpg" },
    { id: 9, titulo: "The Number of the Beast", artista: "Iron Maiden", ano: "1982", preco: "R$ 215,00", categoria: "disco", peso: 450, estado: "EE", capa: "fotos/prod-9-frente.jpg", verso: "fotos/prod-9-verso.jpg" },
    { id: 10, titulo: "Thriller", artista: "Michael Jackson", ano: "1982", preco: "R$ 160,00", categoria: "disco", peso: 450, estado: "EE", capa: "fotos/prod-10-frente.jpg", verso: "fotos/prod-10-verso.jpg" },
    { id: 11, titulo: "Like a Virgin", artista: "Madonna", ano: "1984", preco: "R$ 150,00", categoria: "disco", peso: 450, estado: "EE", capa: "fotos/prod-11-frente.jpg", verso: "fotos/prod-11-verso.jpg" },
    { id: 12, titulo: "Ziggy Stardust", artista: "David Bowie", ano: "1972", preco: "R$ 200,00", categoria: "disco", peso: 450, estado: "EE", capa: "fotos/prod-12-frente.jpg", verso: "fotos/prod-12-verso.jpg" },
    { id: 13, titulo: "The Doors", artista: "The Doors", ano: "1967", preco: "R$ 185,00", categoria: "disco", peso: 450, estado: "EE", capa: "fotos/prod-13-frente.jpg", verso: "fotos/prod-13-verso.jpg" },
    { id: 14, titulo: "Are You Experienced", artista: "Jimi Hendrix", ano: "1967", preco: "R$ 195,00", categoria: "disco", peso: 450, estado: "LAC", capa: "fotos/prod-14-frente.jpg", verso: "fotos/prod-14-verso.jpg" },
    { id: 15, titulo: "Exodus", artista: "Bob Marley", ano: "1977", preco: "R$ 170,00", categoria: "disco", peso: 450, estado: "EE", capa: "fotos/prod-15-frente.jpg", verso: "fotos/prod-15-verso.jpg" },
    { id: 16, titulo: "Cartola II", artista: "Cartola", ano: "1976", preco: "R$ 240,00", categoria: "disco", peso: 450, estado: "EE", capa: "fotos/prod-16-frente.jpg", verso: "fotos/prod-16-verso.jpg" },
    { id: 17, titulo: "Os Mutantes", artista: "Os Mutantes", ano: "1968", preco: "R$ 225,00", categoria: "disco", peso: 450, estado: "EE", capa: "fotos/prod-17-frente.jpg", verso: "fotos/prod-17-verso.jpg" },
    { id: 18, titulo: "Fruto Proibido", artista: "Rita Lee", ano: "1975", preco: "R$ 180,00", categoria: "disco", peso: 450, estado: "EE", capa: "fotos/prod-18-frente.jpg", verso: "fotos/prod-18-verso.jpg" },
    { id: 19, titulo: "Construção", artista: "Chico Buarque", ano: "1971", preco: "R$ 190,00", categoria: "disco", peso: 450, estado: "LAC", capa: "fotos/prod-19-frente.jpg", verso: "fotos/prod-19-verso.jpg" },
    { id: 20, titulo: "Transa", artista: "Caetano Veloso", ano: "1972", preco: "R$ 250,00", categoria: "disco", peso: 450, estado: "EE", capa: "fotos/prod-20-frente.jpg", verso: "fotos/prod-20-verso.jpg" },
    { id: 21, titulo: "Refavela", artista: "Gilberto Gil", ano: "1977", preco: "R$ 195,00", categoria: "disco", peso: 450, estado: "EE", capa: "fotos/prod-21-frente.jpg", verso: "fotos/prod-21-verso.jpg" },
    
    // --- CDs ---
    { id: 22, titulo: "Nevermind", artista: "Nirvana", ano: "1991", preco: "R$ 45,00", categoria: "cd", peso: 150, estado: "EE", capa: "fotos/prod-22-frente.jpg", verso: "fotos/prod-22-verso.jpg" },
    { id: 23, titulo: "Random Access Memories", artista: "Daft Punk", ano: "2013", preco: "R$ 55,00", categoria: "cd", peso: 150, estado: "LAC", capa: "fotos/prod-23-frente.jpg", verso: "fotos/prod-23-verso.jpg" },
    { id: 24, titulo: "Dois", artista: "Legião Urbana", ano: "1986", preco: "R$ 40,00", categoria: "cd", peso: 150, estado: "EE", capa: "fotos/prod-24-frente.jpg", verso: "fotos/prod-24-verso.jpg" },
    { id: 25, titulo: "Cabeça Dinossauro", artista: "Titãs", ano: "1986", preco: "R$ 38,00", categoria: "cd", peso: 150, estado: "EE", capa: "fotos/prod-25-frente.jpg", verso: "fotos/prod-25-verso.jpg" },
    { id: 26, titulo: "Selvagem?", artista: "Os Paralamas", ano: "1986", preco: "R$ 35,00", categoria: "cd", peso: 150, estado: "EE", capa: "fotos/prod-26-frente.jpg", verso: "fotos/prod-26-verso.jpg" },
    { id: 27, titulo: "Calango", artista: "Skank", ano: "1994", preco: "R$ 30,00", categoria: "cd", peso: 150, estado: "EE", capa: "fotos/prod-27-frente.jpg", verso: "fotos/prod-27-verso.jpg" },
    { id: 28, titulo: "Raimundos", artista: "Raimundos", ano: "1994", preco: "R$ 45,00", categoria: "cd", peso: 150, estado: "LAC", capa: "fotos/prod-28-frente.jpg", verso: "fotos/prod-28-verso.jpg" },
    
    // --- DVDs ---
    { id: 29, titulo: "Live at Wembley '86", artista: "Queen", ano: "1986", preco: "R$ 69,00", categoria: "dvd", peso: 180, estado: "EE", capa: "fotos/prod-29-frente.jpg", verso: "fotos/prod-29-verso.jpg" },
    { id: 30, titulo: "Pulse - Live Concert", artista: "Pink Floyd", ano: "1995", preco: "R$ 79,00", categoria: "dvd", peso: 180, estado: "LAC", capa: "fotos/prod-30-frente.jpg", verso: "fotos/prod-30-verso.jpg" },
    { id: 31, titulo: "Acústico MTV", artista: "Charlie Brown Jr", ano: "2003", preco: "R$ 60,00", categoria: "dvd", peso: 180, estado: "EE", capa: "fotos/prod-31-frente.jpg", verso: "fotos/prod-31-verso.jpg" },
    { id: 32, titulo: "Live in Tokyo", artista: "Guns N' Roses", ano: "1992", preco: "R$ 65,00", categoria: "dvd", peso: 180, estado: "EE", capa: "fotos/prod-32-frente.jpg", verso: "fotos/prod-32-verso.jpg" },
    
    // --- Colecionáveis ---
    { id: 33, titulo: "Vitrola Portátil Vintage 1970", artista: "Philips / Áudio", ano: "1972", preco: "R$ 850,00", categoria: "colecionavel", peso: 3500, estado: "EE", capa: "fotos/prod-33-frente.jpg", verso: "fotos/prod-33-verso.jpg" },
    { id: 34, titulo: "Poster Star Wars 1977 Emoldurado", artista: "Memorabilia", ano: "1977", preco: "R$ 450,00", categoria: "colecionavel", peso: 1200, estado: "EE", capa: "fotos/prod-34-frente.jpg", verso: "fotos/prod-34-verso.jpg" },
    { id: 35, titulo: "Action Figure Freddie Mercury", artista: "NECA / Queen", ano: "2018", preco: "R$ 320,00", categoria: "colecionavel", peso: 400, estado: "LAC", capa: "fotos/prod-35-frente.jpg", verso: "fotos/prod-35-verso.jpg" },
    { id: 36, titulo: "Toca-Discos Technics SL-1200MK2", artista: "Technics", ano: "1998", preco: "R$ 4.500,00", categoria: "colecionavel", peso: 11000, estado: "EE", capa: "fotos/prod-36-frente.jpg", verso: "fotos/prod-36-verso.jpg" },
    { id: 37, titulo: "Aphrodite's Child (Disque d'Or)", artista: "Aphrodite's Child", ano: "1975", preco: "R$ 200,00", categoria: "disco", peso: 450, estado: "EE", capa: "fotos/prod-37-frente.jpeg", verso: "fotos/prod-37-verso.jpeg" },
];